### ISSUE TITLE
Support of Apps

### ISSUE THREAD

**Issue by Qstick** [anandslab/deployarr#12]
Hi, Wondering why you would donate to the apps that you are building your product around, and then pull the money back shortly after? Seems a bit odd. 

![image](https://github.com/user-attachments/assets/3d4548a3-fb29-445b-a548-eeb558e7151a)

**Comment by anandslab** [comment]
Valid question, it is because when I first made the contributions, I did not know there was an organization feature in OpenCollective. I wanted allow Deployarr-sponsored contributions to be in one bucket. So, I setup and Organization for Deployarr and re-setup my contributions and contributed 3X more. 

![deployarr opencollective](https://github.com/user-attachments/assets/e8d31e32-14c0-4f52-a481-1ab3252f796e)

**Comment by anandslab** [comment]
@Qstick Does that answer your question? Let me know if you want to close the question.
